apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  annotations:
     prometheus.io/scrape: 'true'
     prometheus.io/port: "80"          
  name: nginx
spec:
  ports:
  - port: 30322
    protocol: TCP
    targetPort: 80
  selector:
    run: nginx
  type: NodePort
status:
  loadBalancer: {}
