apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: "80"
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  strategy: {}
  template:
    metadata:
      labels:
        app: nginx
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: "80"
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
