apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  annotations:
     prometheus.io/scrape: 'true'
     prometheus.io/port: "80"      
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
