apiVersion: v1
kind: Service
metadata:
  labels:
    app: python-exporter
  name: python-exporter
spec:
  ports:
  - name: server-port
    port: 8000
    protocol: TCP
    targetPort: 8000
  - name: exporter-port
    port: 8001
    protocol: TCP
    targetPort: 8001
  selector:
    app: python-exporter
  type: NodePort
status:
  loadBalancer: {}