#! /usr/bin/env python3

from subprocess import run
from argparse import ArgumentParser
import logging
import sys

parser = ArgumentParser(description="Startup script for launching prometheus ")

parser.add_argument("-s","--sleep",help="Launch instance with sleep as main process",action="store_true")
parser.add_argument("-t","--test",help="Launch instance with minimal configuration",action="store_true")

args = parser.parse_args()

if args.sleep:
    to_run_command_list = ["sleep", "infinity"]
    file_handler = logging.FileHandler(filename='tmp.log')
    stdout_handler = logging.StreamHandler(sys.stdout)
    handlers = [file_handler, stdout_handler]
    logging.basicConfig(
    level=logging.INFO, 
    format='[%(asctime)s] {%(filename)s:%(lineno)d} %(levelname)s - %(message)s',
    handlers=handlers
)

logger = logging.getLogger('LOGGER_NAME')


if args.test:
    to_run_command_list = ["prometheus","--config.file=/home/prometheus/prometheus-extracted/prometheus.yml",
    "--storage.tsdb.path=/home/prometheus/persistent","--web.console.libraries=/home/prometheus/prometheus-extracted/console_libraries",
    "--web.console.templates=/home/prometheus/prometheus-extracted/consoles"]

run(to_run_command_list)



